import { Person, RelationshipEdge, Memory } from './types';

export const INITIAL_PEOPLE: Person[] = [
  {
    id: 'user-0',
    name: '나 (대표님)',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    phone: '010-1234-5678',
    title: 'HBOS 마스터 & 비즈니스 대표',
    group: '가족',
    firstMeetingDate: '1980-01-01',
    firstMeetingLocation: '서울',
    firstMeetingContext: '본인 프로필',
    tags: ['마스터', '비즈니스'],
    isUser: true,
  },
  {
    id: 'person-1',
    name: '김철수 대표',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    phone: '010-9876-5432',
    title: '메나테크 골드 디렉터 / (주)유진 대표',
    group: '사업 파트너',
    firstMeetingDate: '2023-05-12',
    firstMeetingLocation: '강남 메나테크 센터 3층 대회의실',
    firstMeetingContext: '장원술 목사님의 강력 추천 소개로 간 건강 및 글리코 사업 상담을 위해 첫 미팅을 가짐.',
    tags: ['메나테크', '간건강', '양자검사', '골드디렉터'],
    notes: '음료는 따뜻한 미온수를 좋아하심. 딸 김서연 님 해외 유학 중.',
    physiognomy: {
      forehead: '이마가 넓고 곧게 뻗어 명예운과 리더십이 뛰어남.',
      eyes: '눈동자가 맑고 혜안이 있어 추진력과 도의를 중시하는 타입.',
      nose: '코끝이 두툼하여 재물 복과 신체 관상 기능이 매우 양호함.',
      mouth: '입꼬리가 위로 올라가 인복이 많고 말년에 따르는 파트너가 많음.',
      summary: '신뢰감과 추진력을 겸비한 전형적인 비즈니스 리더 관상. 정직한 설명에 마음을 엽니다.',
      icebreakerTips: [
        '최근 간 건강 개선 추세와 글리코 영양소 섭취 소감을 먼저 여쭤보세요.',
        '해외 유학 중인 딸 서연 양 소식을 물어보면 분위기가 매우 화기애애해집니다.',
      ],
      healthNote: '간 해독 수치 관리가 필요하며 트루퓨어 섭취를 추천.',
    },
  },
  {
    id: 'person-2',
    name: '이영희 님',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    phone: '010-5555-4321',
    title: '교회 봉사팀장 / 김철수 대표 아내',
    group: '교회 성도',
    firstMeetingDate: '2023-08-20',
    firstMeetingLocation: '소망교회 카페',
    firstMeetingContext: '주일 예배 후 김철수 대표 부부와 함께 식사하며 인사함.',
    tags: ['교회', '소망교회', '배우자', '원예'],
    notes: '화초 가꾸기와 플라워 아트를 좋아하심.',
    physiognomy: {
      forehead: '이마가 동글고 인자하여 가정에 화목을 불러오는 관상.',
      eyes: '눈웃음이 밝고 온화하여 주위 사람들을 편안하게 해줌.',
      nose: '매끄럽고 단정하여 건강과 절약 정신이 우수함.',
      mouth: '입술 두께가 적당하여 솔직하고 진정성 있는 대화를 선호함.',
      summary: '배려심이 깊고 온화한 덕모 관상. 편안한 안부 인사로 대화를 시작하세요.',
      icebreakerTips: [
        '최근 교회 봉사 활동이나 화단 정원 가꾸기 이야기를 꺼내보세요.',
      ],
      healthNote: '소화기 및 위장 케어가 도움 됨 (엠브로토스 AO 추천).',
    },
  },
  {
    id: 'person-3',
    name: '박찬호 사장',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    phone: '010-3333-8888',
    title: '용산 물류 시스템 대표 / 대표님 고교 동창',
    group: '고교 동창',
    firstMeetingDate: '1995-03-02',
    firstMeetingLocation: '중앙고등학교 교실',
    firstMeetingContext: '고등학교 1학년 같은 반으로 만나 30년 넘게 우정을 이어오는 불알친구.',
    tags: ['고교동창', '30년지기', '골프', '물류'],
    notes: '주말마다 등산과 골프를 즐김. 막걸리 좋아함.',
    physiognomy: {
      forehead: '넓은 이마와 강한 눈썹으로 의리와 의지가 강함.',
      eyes: '선하고 깊은 눈매로 오랜 우정을 소중히 여김.',
      nose: '선이 굵고 곧아 고집이 있으나 의리를 먼저 챙김.',
      mouth: '말투가 시원시원하고 서글서글함.',
      summary: '의리와 정이 넘치는 영원한 고교 동창 관상.',
      icebreakerTips: [
        '고교 시절 추억 이야기나 지난달 동창회 골프 라운딩 이야기를 해보세요.',
      ],
      healthNote: '관절 및 연골 건강 케어 추천 (엠브로토스 파이토클렌즈).',
    },
  },
  {
    id: 'person-4',
    name: '박지민 팀장',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    phone: '010-7777-1111',
    title: '(주)유진 수석 마케팅 팀장 / 박찬호 사장 사촌동생',
    group: '친척',
    firstMeetingDate: '2024-02-14',
    firstMeetingLocation: '강남 루프탑 카페',
    firstMeetingContext: '박찬호 사장이 사촌 동생이라고 소개해주어 마케팅 컨설팅 조언을 나눔.',
    tags: ['박찬호사촌', '마케팅', '디지털'],
    notes: '인스타그램 및 SNS 마케팅에 능통함.',
    physiognomy: {
      forehead: '지적이고 스마트한 이마로 트렌드 감각이 매우 뛰어남.',
      eyes: '총기가 넘치며 감각적이고 논리적인 대화를 좋아함.',
      nose: '날렵하고 똑부러지는 스타일.',
      mouth: '표현력이 밝고 명쾌함.',
      summary: '감각적이고 트렌디한 마케터 관상.',
      icebreakerTips: [
        '최근 SNS 마케팅 동향이나 사촌 오빠 박찬호 사장 안부를 물어보세요.',
      ],
      healthNote: '눈 피로 및 피로회복 케어 추천.',
    },
  },
  {
    id: 'person-5',
    name: '장원술 목사님',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
    phone: '010-4444-9999',
    title: '은혜교회 담임목사 / 대표님의 먼 일가 삼촌',
    group: '가족',
    firstMeetingDate: '2010-09-15',
    firstMeetingLocation: '은혜교회 목양실',
    firstMeetingContext: '가족 친척 모임에서 인사 후 목회 및 건강 영양 솔루션 동역자로 인연을 맺음.',
    tags: ['목사님', '친척삼촌', '은혜교회', '영양상담'],
    notes: '목소리가 인자하시고 건강에 관심이 많으심.',
    physiognomy: {
      forehead: '덕망이 높은 성현의 이마 관상.',
      eyes: '자애롭고 경청하는 눈매.',
      nose: '건강하고 원만한 호인형 관상.',
      mouth: '축복과 긍정의 메시지를 주는 명품 입술.',
      summary: '덕망과 신앙이 깊은 목회자 관상.',
      icebreakerTips: ['성경 말씀 구절이나 교우들의 건강 상담 경험을 나눠보세요.'],
      healthNote: '면역 기능 케어 (엠브로토스 콤플렉스 파우더).',
    },
  },
];

export const INITIAL_EDGES: RelationshipEdge[] = [
  // 1. 나 ➔ 박찬호 (고교 동창)
  {
    id: 'edge-1',
    sourceId: 'user-0',
    targetId: 'person-3',
    relationType: 'friend',
    label: '30년지기 고교 동창',
    notes: '중앙고 1학년 같은 반 친구',
  },
  // 2. 박찬호 ➔ 박지민 (사촌 관계)
  {
    id: 'edge-2',
    sourceId: 'person-3',
    targetId: 'person-4',
    relationType: 'cousin',
    label: '사촌 동생',
    notes: '박찬호 사장의 친삼촌 딸',
  },
  // 3. 박지민 ➔ 김철수 대표 (직장 상사 & 직동)
  {
    id: 'edge-3',
    sourceId: 'person-4',
    targetId: 'person-1',
    relationType: 'colleague',
    label: '직장 상사 (팀장-대표)',
    notes: '(주)유진 마케팅 팀장으로 김철수 대표 밑에서 근무',
  },
  // 4. 나 ➔ 장원술 목사님 (친척 삼촌)
  {
    id: 'edge-4',
    sourceId: 'user-0',
    targetId: 'person-5',
    relationType: 'relative',
    label: '친척 삼촌 (오촌)',
    notes: '가문 친척 어르신',
  },
  // 5. 장원술 목사님 ➔ 김철수 대표 (소개자 관계)
  {
    id: 'edge-5',
    sourceId: 'person-5',
    targetId: 'person-1',
    relationType: 'introducer',
    label: '첫 만남 소개자',
    notes: '장원술 목사님이 김철수 대표를 대표님께 소개해 줌',
  },
  // 6. 김철수 대표 ➔ 이영희 님 (부부)
  {
    id: 'edge-6',
    sourceId: 'person-1',
    targetId: 'person-2',
    relationType: 'spouse',
    label: '부부 (아내)',
    notes: '2001년 결혼',
  },
];

export const INITIAL_MEMORIES: Memory[] = [
  {
    id: 'mem-1',
    personId: 'person-1',
    date: '2023-05-12',
    title: '강남 센터 첫 미팅 & 양자검사 상담',
    content: '장원술 목사님 소개로 첫 만남. 간 해독 지수가 3.42로 나와 걱정하셨으나, 트루퓨어 및 글리코 영양소 3개월 솔루션을 제시해 드림. 매우 긍정적 반응.',
    image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&q=80&w=400',
    location: '강남 센터 3층',
  },
  {
    id: 'mem-2',
    personId: 'person-1',
    date: '2023-11-04',
    title: '메나테크 골드 디렉터 승급 축하',
    content: '김철수 대표님이 사업 입문 6개월 만에 골드 디렉터 승급! 파트너분들과 모여 비전 선포식 및 가벼운 축하 식사 자리를 가짐.',
    image: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&q=80&w=400',
    location: '인터콘티넨탈 호텔 뷔페',
  },
  {
    id: 'mem-3',
    personId: 'person-3',
    date: '2024-04-15',
    title: '봄맞이 동창회 골프 라운딩 & 막걸리 타임',
    content: '찬호와 함께 남한산성 근처 라운딩 후 산장에서 막걸리 한잔. 찬호가 자기 사촌 동생(박지민 팀장) 마케팅 조언 좀 해달라고 부탁함.',
    image: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?auto=format&fit=crop&q=80&w=400',
    location: '남한산성 골프클럽',
  },
];
